### ISSUE TITLE
woof today available under CC-BY?

### ISSUE THREAD

**Issue by shannonpileggi** [allisonhorst/stats-illustrations#14]
Hi Allison - I hope you are well!  I love all of your incredible artwork so much, and I lean on it heavily to help make my blog friendly and fun. Is the [woof today](https://twitter.com/allison_horst/status/1448134445559472456) illustration available under the CC-BY license? I would love to use it in an upcoming blog post. Apologies if it is in the `README` and I didn't see it!

**Comment by allisonhorst** [comment]
Hi Shannon - Oh yep that one is definitely also available by CC-BY, feel free to use it in your post! I must have forgotten to add it here, thanks for the heads up :)

**Comment by shannonpileggi** [comment]
Super, thank you!
