### ISSUE TITLE
README as gallery

### ISSUE THREAD

**Issue by jennybc** [allisonhorst/stats-illustrations#3]
You've got so much fantastic stuff here!

It would be interesting to adopt a "README as clickable gallery" approach in the (sub)directories.

I've done something similar here, in case it helps:

https://github.com/jennybc/orly-full-res/blob/master/README.Rmd

And the rendered result is pretty satisfying:

https://github.com/jennybc/orly-full-res#readme

**Comment by allisonhorst** [comment]
YES. So much more useful, I'll update it this week!

**Comment by allisonhorst** [comment]
Thank you @jennybc, you're awesome.
