### ISSUE TITLE
Wrong link to Spanish translations

### ISSUE THREAD

**Issue by arcruz0** [allisonhorst/stats-illustrations#7]
The link to the Spanish translations is currently listed as  [https://github.com/allisonhorst/stats-illustrations/tree/master/rstats-artwork-ES**rstats-artwork-ES**](https://github.com/allisonhorst/stats-illustrations/tree/master/rstats-artwork-ESrstats-artwork-ES) in the README, when it should be [https://github.com/allisonhorst/stats-illustrations/tree/master/rstats-artwork-ES](https://github.com/allisonhorst/stats-illustrations/tree/master/rstats-artwork-ES).

Thank you very much for the awesome illustrations!

**Comment by allisonhorst** [comment]
Thank you @arcruz0 !!! Fixed!
